<?php
/**
 * 经销商档案信息
 *
 * @copyright  Copyright (c) 2005-2010 ShopEx Technologies Inc. (http://www.shopex.cn)
 * @license  http://ecos.shopex.cn/ ShopEx License
 */

$db['member_drp']=array (
  'columns' =>
  array (
    'member_drp_id' =>
    array (
      'type' => 'number',
      'required' => true,
      'pkey' => true,
      'extra' => 'auto_increment',
      'label' => 'ID',
      'width' => 110,
      'editable' => false,
      'in_list' => false,
      'default_in_list' => false,
    ),
    'member_id' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('用户id'),
      'sdfpath' => 'members/member_id',
      'width' => 75,
      'order' => 40,
      'type' => 'table:members',
      'editable' => true,
      'in_list' => true,
      'default_in_list' => true,
    ),
    'member_name' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('所属用户'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(50)',
      'editable' => true,
      'filtertype' => 'bool',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
     'user_money' =>
    array (
      'type' => 'decimal(20,3) unsigned',
      'default' => '0.00',
      'required' => true,
      'label' => app::get('b2c')->_('佣金金额'),
      'width' => 110,
      'editable' => false,
      'filtertype' => 'number',
      'in_list' => true,
      'comment' => app::get('b2c')->_('佣金金额,用于存放所有佣金'),
    ),
    'appstatus' =>
    array (
      'type' =>
      array (
        0 => app::get('b2c')->_('未提交'), 
        1 => app::get('b2c')->_('已提交'),
        2 => app::get('b2c')->_('已审核'),
        3 => app::get('b2c')->_('已拒绝'),
        4 => '-',
      ),
      'default' => '0',
      'required' => true,
      'label' => app::get('b2c')->_('申请状态'),
      'order' => 30,
      'width' => 40,
      'editable' => true,
      'filtertype' => 'yes',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'real_name' =>
    array (
      'type' => 'varchar(50)',
      'label' => app::get('b2c')->_('姓名'),
      'width' => 75,
      'searchtype' => 'has',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'is_title'=>true,
      'default_in_list' => false,
    ),  
    'tel' =>
    array (
      'type' => 'varchar(50)',
      'label' => app::get('b2c')->_('电话'),
      'width' => 110,
      'sdfpath' => 'phone/telephone',
      'searchtype' => 'has',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => false,
    ),
    'gender' =>
    array (
      'type' => 'varchar(50)',
      'sdfpath' => 'profile/gender',
      'default' => '2',
      'required' => true,
      'label' => app::get('b2c')->_('性别'),
      'order' => 30,
      'width' => 40,
      'editable' => true,
      'filtertype' => 'yes',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'birthday' =>
    array (
      'label' => app::get('b2c')->_('生日'),
      'width' => 75,
      'type' => 'date',
      'editable' => false,
      'filtertype' => 'date',
      'filterdefault' => true,
      'in_list' => true,
      'default_in_list' => true,
      'comment' => app::get('b2c')->_('生日'),
    ), 
    'email' => array(
        'type'=>'varchar(100)',
        'in_list' => true,
        'label' => 'Email',
        'default_in_list' => true,
        'comment' => app::get('b2c')->_('邮箱'),
    ),
    'weixin' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('微信号'),
      'searchtype' => 'has',
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(50)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'qq' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('QQ'),
      'searchtype' => 'has',
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(50)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'address' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('联系地址'),
      'searchtype' => 'has',
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(100)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'card' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('身份证号'),
      'searchtype' => 'has',
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(20)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'card_img' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('身份证图片'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(200)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'is_store' =>
    array (
      'type' =>
      array (
        0 => app::get('b2c')->_('否'),
        1 => app::get('b2c')->_('是'),
      ),
      'default' => '1',
      'required' => true,
      'label' => app::get('b2c')->_('是否有店铺'),
      'order' => 30,
      'width' => 40,
      'editable' => true,
      'filtertype' => 'yes',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'stroe_info' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('网店信息'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(500)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'social_networks' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('社群网络'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(20)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
   'networks_url' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('店铺链接'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(200)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'oper_years' =>
    array (
      'type' => 'number',
      'default' => '0',
      'label' => app::get('b2c')->_('运营年数'),
      'required' => true,
      'width' => 110,
      'filtertype' => 'number',
      'editable' => false,
      'in_list' => true,
    ),
    'store_type' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('店铺类别'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(50)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'goods_type_count' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('商品种类数'),
      'width' => 75,
      'order' => 40,
      'type' => 'number',
      'editable' => true,
      'filtertype' => 'number',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'country' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('所属国家'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(50)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'sale_money' =>
    array (
      'type' => 'money',
      'default' => '0',
      'label' => app::get('b2c')->_('每月销售额'),
      'required' => true,
      'width' => 110,
      'filtertype' => 'number',
      'editable' => false,
      'in_list' => true,
    ),
    'fans_count' =>
    array (
      'type' => 'number',
      'default' => '0',
      'label' => app::get('b2c')->_('粉丝数量'),
      'required' => true,
      'width' => 110,
      'filtertype' => 'number',
      'editable' => false,
      'in_list' => true,
    ),
    'zan_count' =>
    array (
      'type' => 'number',
      'default' => '0',
      'label' => app::get('b2c')->_('得赞数'),
      'required' => true,
      'width' => 110,
      'filtertype' => 'number',
      'editable' => false,
      'in_list' => true,
    ),
    'frequency' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('发文频率'),
      'width' => 75,
      'order' => 40,
      'type' => 'number',
      'editable' => true,
      'filtertype' => 'number',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'is_true_store' =>
    array (
      'type' =>
      array (
        0 => app::get('b2c')->_('否'),
        1 => app::get('b2c')->_('是'),
      ),
      'sdfpath' => 'profile/gender',
      'default' => '1',
      'required' => true,
      'label' => app::get('b2c')->_('是否有实体店铺'),
      'order' => 30,
      'width' => 40,
      'editable' => true,
      'filtertype' => 'yes',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'tstroe_info' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('网店信息'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(500)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
    'toper_years' =>
    array (
      'type' => 'number',
      'default' => '0',
      'label' => app::get('b2c')->_('运营年数'),
      'required' => true,
      'width' => 110,
      'filtertype' => 'number',
      'editable' => false,
      'in_list' => true,
    ),
    'store_address' =>
    array (
      'default' => 0,
      'label' => app::get('b2c')->_('所在地'),
      'width' => 75,
      'order' => 40,
      'type' => 'varchar(50)',
      'editable' => true,
      'filtertype' => 'normal',
      'filterdefault' => 'true',
      'in_list' => true,
      'default_in_list' => true,
    ),
   ),
  'engine' => 'innodb',
  'version' => '$Rev: 44523 $',
  'comment' => app::get('b2c')->_('经销商信息'),
);
